<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE studentlist [
<!ELEMENT studentlist (student*)>
<!ELEMENT student (id, regno, name, avg, dob, time, mobileno, distinction) >
<!ELEMENT id (#PCDATA)>
<!ELEMENT regno (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT avg (#PCDATA)>
<!ELEMENT dob (#PCDATA)>
<!ELEMENT time (#PCDATA)>
<!ELEMENT mobileno (#PCDATA)>
<!ELEMENT distinction (#PCDATA)>
]>
<studentlist>
    <student>
        <id>66</id>
        <regno>1920</regno>
        <name>Nikhil</name>
        <avg>98</avg>
        <dob>27-05-2002</dob>
        <time>2:00 PM</time>
        <mobileno>456456</mobileno>
        <distinction>Pass</distinction>
    </student>
    <student>
        <id>66</id>
        <regno>1920</regno>
        <name>Nikhil</name>
        <avg>98</avg>
        <dob>27-05-2002</dob>
        <time>2:00 PM</time>
        <mobileno>456456</mobileno>
        <distinction>Pass</distinction>
    </student>
    <student>
        <id>66</id>
        <regno>1920</regno>
        <name>Nikhil</name>
        <avg>98</avg>
        <dob>27-05-2002</dob>
        <time>2:00 PM</time>
        <mobileno>456456</mobileno>
        <distinction>Pass</distinction>
    </student>
    <student>
        <id>66</id>
        <regno>1920</regno>
        <name>Nikhil</name>
        <avg>98</avg>
        <dob>27-05-2002</dob>
        <time>2:00 PM</time>
        <mobileno>456456</mobileno>
        <distinction>Pass</distinction>
    </student>
    <student>
        <id>66</id>
        <regno>1920</regno>
        <name>Nikhil</name>
        <avg>98</avg>
        <dob>27-05-2002</dob>
        <time>2:00 PM</time>
        <mobileno>456456</mobileno>
        <distinction>Pass</distinction>
    </student>
</studentlist>