=== Nikhil1920/EP_Practical/EP_Prac-2/student.dtd
<!ELEMENT student (id, regno, name, avg, dob, time, mobileno, distinction) >
<!ELEMENT id (#PCDATA)>
<!ELEMENT regno (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT avg (#PCDATA)>
<!ELEMENT dob (#PCDATA)>
<!ELEMENT time (#PCDATA)>
<!ELEMENT mobileno (#PCDATA)>
<!ELEMENT distinction (#PCDATA)>

=== Nikhil1920/EP_Practical/EP_Prac-2/student_dtd_external.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE student SYSTEM "student.dtd">
<student>
    <id>66</id>
    <regno>1920</regno>
    <name>Nikhil</name>
    <avg>98</avg>
    <dob>27-05-2002</dob>
    <time>2:00 PM</time>
    <mobileno>456456</mobileno>
    <distinction>Pass</distinction>
</student>
