=== Nikhil1920/EP_Practical/EP_Prac-2/post_lab-2/student.xsd
<?xml version="1.0"?>

<xs:schema xmlns:xs = "http://www.w3.org/2001/XMLSchema">
    <xs:element name = 'studentlist'>
        <xs:complexType>
            <xs:sequence>
                <xs:element name = 'student' type = 'StudentType' minOccurs = '0' 
                maxOccurs = 'unbounded' />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name = "StudentType">
        <xs:sequence>
            <xs:element name = "id" type = "xs:positiveInteger"/>
            <xs:element name = "regno" type = "xs:positiveInteger"/>
            <xs:element name = "name" type = "xs:string"/>
            <xs:element name = "avg" type = "xs:positiveInteger"/>
            <xs:element name = "dob" type = "xs:date"/>
            <xs:element name = "time" type = "xs:time"/>
            <xs:element name = "mobileno" type = "xs:positiveInteger"/>
            <xs:element name = "distinction" type = "xs:string"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== Nikhil1920/EP_Practical/EP_Prac-2/post_lab-2/student.xml
<?xml version="1.0" encoding="UTF-8"?>
<studentlist xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="student.xsd">
    <student>
        <id>66</id>
        <regno>1920</regno>
        <name>Nikhil</name>
        <avg>98</avg>
        <dob>2002-05-27</dob>
        <time>02:00:00</time>
        <mobileno>456456</mobileno>
        <distinction>Pass</distinction>
    </student>
    <student>
        <id>66</id>
        <regno>1920</regno>
        <name>Nikhil</name>
        <avg>98</avg>
        <dob>2002-05-27</dob>
        <time>02:00:00</time>
        <mobileno>456456</mobileno>
        <distinction>Pass</distinction>
    </student>
    <student>
        <id>66</id>
        <regno>1920</regno>
        <name>Nikhil</name>
        <avg>98</avg>
        <dob>2002-05-27</dob>
        <time>02:00:00</time>
        <mobileno>456456</mobileno>
        <distinction>Pass</distinction>
    </student>
    <student>
        <id>66</id>
        <regno>1920</regno>
        <name>Nikhil</name>
        <avg>98</avg>
        <dob>2002-05-27</dob>
        <time>02:00:00</time>
        <mobileno>456456</mobileno>
        <distinction>Pass</distinction>
    </student>
    <student>
        <id>66</id>
        <regno>1920</regno>
        <name>Nikhil</name>
        <avg>98</avg>
        <dob>2002-05-27</dob>
        <time>02:00:00</time>
        <mobileno>456456</mobileno>
        <distinction>Pass</distinction>
    </student>
</studentlist>
